### PR TITLE
refactor: switch to `tiny-keccak` library

### PR DESCRIPTION
**Pull request by Daniel-Aaron-Bloom**
Improves performance by switching to the underlying library to do incremental hashing without allocation (i.e. no more temporary `Vec`s)

### CODE REVIEW

**Review by muursh — COMMENTED** [review]
I'm hesitant over this. It's been a long time since `tiny-keccak` work done on it and I feel `keccak-hash` is a safer bet maintenance wise.

**Comment by Daniel-Aaron-Bloom** [comment]
I chose `tiny-keccak` because `keccak-hash` utilizes it for the actual hashing implementation.

What makes you feel like the maintenance on `keccak-hash` will be better than `tiny-keccak`? It doesn't look like it's had any meaningful code updates [since 2020](https://github.com/paritytech/parity-common/commits/master/keccak-hash/src), and honestly as far as it's used here, it seems like just ~100 line wrapper around `tiny-keccak`.

I'd be happy to make PR to use something like `sha3` instead if maintenance is a concern.

**Comment by muursh** [comment]
My main argument would be that I expect Parity to be more likely to maintain their crate, which makes my life easier long term. I'm open to a change if you have some convincing benchmarks or the like though

**Review by Nashtare — COMMENTED** [review]
I would also tend to favor the library developed by Parity as opposed to `tiny-keccak` which hasn't been maintained in years.

**Comment by muursh** [comment]
I'm going to close this for now given the consensus that `tiny-keccak` has a higher chance of being problematic at some point.

**Pull request closed without merging**
