### PR TITLE
Fix CTL grouping

### PR DESCRIPTION
**Pull request by matthiasgoergens**
See https://github.com/0xPolygonZero/plonky2/issues/1582

### CODE REVIEW

**Review by Nashtare — APPROVED** [review]

**Comment by matthiasgoergens** [comment]
Looks like I need to fix the no-std tests. Can do.

**Review by muursh — APPROVED** [review]

**Comment by Nashtare** [comment]
@matthiasgoergens any blocker on this?

**Comment by matthiasgoergens** [comment]
Sorry, I just need to spend some time on it. Will do today.

**Comment by muursh** [comment]
Hey @matthiasgoergens I was just wondering if this is something you're intending to get merged?

**Comment by matthiasgoergens** [comment]
Thanks for reminding me. Let me get this PR back in shape.

**Comment by Nashtare** [comment]
Closing for inactivity.

**Pull request closed without merging**
