### PR TITLE
Add some documentation in EVM crate

### PR DESCRIPTION
**Pull request by Nashtare**
@pgebheim That's the branch we started adding documentation on.
We didn't touch the kernel at all, nor the specs pdf (apart from adding an empty section for the new table).

### CODE REVIEW

**Comment by pgebheim** [comment]
@Nashtare @LindaGuiga Would you be okay with merging this as is and then adding more docs?

**Comment by Nashtare** [comment]
Sure, let me just rebase first.

**Comment by Nashtare** [comment]
@pgebheim should be ready for merging if you want!

**Review by dvdplm — COMMENTED** [review]
It'd be good to use the "`[SomeItemInScope]`"-syntax to leverage rustdoc auto-linking feature. So rather than 
```
/// Something something returns `CrossTableLookups`.
```

…you'd write 

```
/// Something something returns [`CrossTableLookups`].
```

**Comment by Nashtare** [comment]
@dvdplm Agreed, though apart from the serialization module inside `plonky2` crate, this is never used, and the `plonky2_evm` crate hasn't been published on `crates.io`, so I'd rather go for a dedicated PR updating _all_ references with that suggestion (not just on `plonky2_evm`). Does that make sense to you?
cc @pgebheim

**Pull request merged**
