### PR TITLE
SMT deletion

### PR DESCRIPTION
**Pull request by wborgeaud**

### CODE REVIEW

**Review by Nashtare — APPROVED** [review]
Thanks William! Sorry it took me longer than planned, I ended up forgetting this PR 🤦🏼‍♂️

**Comment by pgebheim** [comment]
@wborgeaud -- looks like this can be merged?

**Comment by wborgeaud** [comment]
> @wborgeaud -- looks like this can be merged?

I'm getting some failing tests in the test suite due to SMT deletion, so will try to fix those before merging this PR.

**Comment by Nashtare** [comment]
@wborgeaud Is that on a public branch? I could give it a look as well

**Comment by wborgeaud** [comment]
> @wborgeaud Is that on a public branch? I could give it a look as well

Thanks! It is now ;) 
I pushed the modified test runner to https://github.com/0xPolygonZero/evm-tests/tree/type2 and the Plonky2 branch I'm testing against is https://github.com/0xPolygonZero/plonky2/tree/type2/testing which is the combination of this PR and #1333.

I haven't run the full test suite, but some failing tests I'm seeing in `stCallCodes` are
```
callcodeInInitcodeToExistingContractWithValueTransfer_d0g0v0_Shanghai, callcodeDynamicCode2SelfCall_d0g0v0_Shanghai, callcodeInInitcodeToExisContractWithVTransferNEMoney_d1g0v0_Shanghai, callcodeInInitcodeToExisContractWithVTransferNEMoney_d0g0v0_Shanghai, callcallcodecallcode_011_OOGMAfter_d0g0v0_Shanghai, callcodecallcodecall_110_OOGMAfter_d0g0v0_Shanghai, callcodeInInitcodeToExistingContract_d1g0v0_Shanghai, callcodeInInitcodeToExistingContract_d0g0v0_Shanghai, callcodeInInitcodeToEmptyContract_d1g0v0_Shanghai, callcodeInInitcodeToEmptyContract_d0g0v0_Shanghai, callcodeDynamicCode_d1g0v0_Shanghai, callcodeDynamicCode_d2g0v0_Shanghai, callcodeDynamicCode_d3g0v0_Shanghai, callcodeDynamicCode_d0g0v0_Shanghai, callcodecallcodecallcode_111_OOGMAfter_d0g0v0_Shanghai, callcallcodecall_010_OOGMAfter_d0g0v0_Shanghai, callcall_00_OOGE_d0g0v0_Shanghai
```

**Comment by wborgeaud** [comment]
Some failing tests with the latest `type2/testing` in `stCreate`:
```
CreateResults_d23g0v0_Shanghai, CreateResults_d19g0v0_Shanghai, CreateResults_d25g0v0_Shanghai, CreateResults_d24g0v0_Shanghai, CreateResults_d21g0v0_Shanghai, CreateResults_d18g0v0_Shanghai, CreateResults_d20g0v0_Shanghai, CreateResults_d22g0v0_Shanghai, RevertInCreateInInitCreate2_d0g0v0_Shanghai, create2collisionStorage_d0g0v0_Shanghai, create2collisionStorage_d1g0v0_Shanghai, create2collisionStorage_d2g0v0_Shanghai
```

**Comment by wborgeaud** [comment]
Merging this and opening another PR with several bug fixes.

**Pull request merged**
